### ISSUE TITLE
pyql building issue / Cannot assign type 'vector[Rate]' to 'vector[double]'

### ISSUE THREAD

**Issue by ianyunxiong** [enthought/pyql#156] opened 2016-07-30 17:12 UTC
When I used boost 1.60, quantlib 1.8, and Cython 0.24 to build the latest pyql on windows 10 x64, I had the following error message:

```
Error compiling Cython file:
------------------------------------------------------------
...
        self._trait = interpolator
        if interpolator == Linear:
            self._thisptr = shared_ptr[_dts.DefaultProbabilityTermStructure](
                new _ihc.InterpolatedHazardRateCurve[_ihc.Linear](
                    _dates, hazard_rates,
                                       ^
------------------------------------------------------------

quantlib\termstructures\credit\interpolated_hazardrate_curve.pyx:51:40: Cannot assign type 'vector[Rate]' to 'vector[double]'

Error compiling Cython file:
------------------------------------------------------------
...
                    c_cal)
            )
        elif interpolator == LogLinear:
            self._thisptr = shared_ptr[_dts.DefaultProbabilityTermStructure](
                new _ihc.InterpolatedHazardRateCurve[_ihc.LogLinear](
                    _dates, hazard_rates,
                                       ^
------------------------------------------------------------

quantlib\termstructures\credit\interpolated_hazardrate_curve.pyx:58:40: Cannot assign type 'vector[Rate]' to 'vector[double]'

Error compiling Cython file:
------------------------------------------------------------
...
                    c_cal)
            )
        elif interpolator == BackwardFlat:
            self._thisptr = shared_ptr[_dts.DefaultProbabilityTermStructure](
                new _ihc.InterpolatedHazardRateCurve[_ihc.BackwardFlat](
                    _dates, hazard_rates,
                                       ^
------------------------------------------------------------

quantlib\termstructures\credit\interpolated_hazardrate_curve.pyx:65:40: Cannot assign type 'vector[Rate]' to 'vector[double]'
Traceback (most recent call last):
  File "setup.py", line 315, in <module>
    ext_modules = collect_extensions(),
  File "setup.py", line 237, in collect_extensions
    , compiler_directives=CYTHON_DIRECTIVES)
  File "D:\Program Files\Python\Python35\lib\site-packages\Cython\Build\Dependencies.py", line 912, in cythonize
    cythonize_one(*args)
  File "D:\Program Files\Python\Python35\lib\site-packages\Cython\Build\Dependencies.py", line 1034, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: quantlib\termstructures\credit\interpolated_hazardrate_curve.pyx

```

could anyone help me, please? many thanks in advance!

**Comment by thrasibule** [comment] 2016-08-02 17:02
I can't reproduce this on linux, so I'll try to setup a windows  environment and see if I can reproduce. In the mean time, try to insert <vector[double]> before hazard_rate. But Rate and double should be equivalent based (see typedef in types.pxi), so I'm not sure what's going on.

**Comment by ianyunxiong** [comment] 2016-08-03 17:11
in interpolated_hazardrate_curve.pyx i changed 'vector[Rate]' into 'vector[double]' then it works.

**Comment by thrasibule** [comment] 2016-08-09 13:35
I wonder if this was fixed in cython 0.24.1. I see this in the changelog: ``Assignments between identical C++ types that were declared with differently typedefed template types could fail`` which seems related.

**Comment by ceaza** [comment] 2016-09-10 17:38
@thrasibule had the issue on linux, upgraded to cython 0.24.1 and build now works.

**Comment by dpinte** [comment] 2016-09-12 07:44
@ceaza thanks, we'll document that cython 0.24.1 is the required cython version!

**Closed** 2016-11-16 16:25 UTC
